version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: database
    volumes:
      - /database:/adahack/postgresql

volumes:
  postgresql_data:
